<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>de.engehausen</groupId>
		<artifactId>treemap.build</artifactId>
		<version>1.1.3-SNAPSHOT</version>
		<relativePath>../treemap.build/pom.xml</relativePath>
	</parent>
	<artifactId>treemap.eclipse</artifactId>
	<packaging>pom</packaging>
	<name>TreeMapEclipse</name>
	<url>https://github.com/smurf667/treemaplib/</url>
	<description>Contains the tree map for Eclipse.</description>
	<properties>
		<local.site>${project.build.directory}/local-site</local.site>
	</properties>
	<dependencies>
		<dependency>
			<groupId>de.engehausen</groupId>
			<artifactId>treemap.core</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>de.engehausen</groupId>
			<artifactId>treemap.swt</artifactId>
			<scope>compile</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack-dependencies</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>unpack-dependencies</goal>
						</goals>
						<configuration>
							<includeGroupIds>de.engehausen</includeGroupIds>
							<excludeTransitive>true</excludeTransitive>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>build-eclipse-site</id>
						<phase>package</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<!-- sorry, very archaic, but it works -->
							<target>
								<mkdir dir="${local.site}"/>
								<copy file="src/main/config/MANIFEST.MF" tofile="${project.build.directory}/manifest.txt"/>
								<copy file="src/main/config/feature.xml" tofile="${project.build.directory}/feature.xml"/>
								<copy file="src/main/config/site.xml" tofile="${local.site}/site.xml"/>
								<replaceregexp match="0\.0\.0" replace="${final.version}" flags="g">
									<fileset dir="${project.build.directory}">
										<include name="manifest.txt"/>
										<include name="feature.xml"/>
										<include name="local-site/site.xml"/>
									</fileset>
								</replaceregexp>
								<!-- build the plugin .jar -->
								<jar destfile="${local.site}/plugins/de.engehausen.treemap_${final.version}.jar" manifest="${project.build.directory}/manifest.txt">
									<fileset dir="${project.build.directory}/dependency" excludes="META-INF"/>
								</jar>
								<!-- build the feature .jar -->
								<jar destfile="${local.site}/features/de.engehausen.treemap_${final.version}.jar" basedir="${project.build.directory}" includes="feature.xml"/>
							</target>
						</configuration>
					</execution>
					<execution>
						<id>copy-eclipse-site</id>
						<phase>install</phase>
						<goals>
							<goal>run</goal>
						</goals>
						<configuration>
							<target>
								<copy file="${project.build.directory}/${project.build.finalName}.zip" tofile="../treemap.build/target/treemap.eclipse-${final.version}-site.zip"/>
							</target>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
						<configuration>
							<appendAssemblyId>false</appendAssemblyId>
							<descriptors>
								<descriptor>${project.basedir}/src/assembly/zip.xml</descriptor>
							</descriptors>
							<finalName>${project.build.finalName}</finalName>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>build-helper-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>regex-property</id>
						<phase>initialize</phase>
						<goals>
							<goal>regex-property</goal>
						</goals>
						<configuration>
							<name>final.version</name>
							<value>${project.version}</value>
							<regex>-SNAPSHOT</regex>
							<replacement/>
							<failIfNoMatch>false</failIfNoMatch>
						</configuration>
					</execution>
					<execution>
						<id>attach-zip</id>
						<phase>package</phase>
						<goals>
							<goal>attach-artifact</goal>
						</goals>
						<configuration>
							<artifacts>
								<artifact>
									<file>${project.build.directory}/${project.build.finalName}.zip</file>
									<type>zip</type>
								</artifact>
							</artifacts>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
